<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Autorelated
 * @version    2.4.12
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
/** @var $abstractBlock Mage_Catalog_Block_Product_List_Related */
$abstractBlock = $this->helper('awautorelated')->getAbstractProductBlock();
?>
<?php if ($this->getCollection() && $this->getCollection()->getSize()) : ?>
    <div class="crosssell">
        <h2><?php echo $this->__('Pensamos que estos te van a encantar') ?></h2>
        <ul id="crosssell-products-list" class="products-grid products-grid--max-3-col">
            <?php foreach ($this->getCollection() as $_item) : ?>
                <li class="item">
                    <a class="product-image" href="<?php echo $abstractBlock->getProductUrl($_item) ?>"
                       title="<?php echo $this->htmlEscape($_item->getName()) ?>"><img
                            src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(420); ?>"
                            width="210" height="210" alt="<?php echo $this->htmlEscape($_item->getName()) ?>"/>
                            <?php // Cucardas (Databunch) on product listing page ?>
                            <?php echo $this->getLayout()->createBlock('labels/catalog_product')->setProduct($_item)->toHtml(); ?>
                            
                    </a>
                    
                    <h3 class="product-name">
                        <a href="<?php echo $abstractBlock->getProductUrl($_item) ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                    </h3>
                    <div class="review">
                        <?php echo $this->getReviewsSummaryHtml($_item, 'default', false)?>
                    </div>
                    <div class="stock">
                    <?php if($_item->getStockItem() && $_item->getStockItem()->getIsInStock()): ?>
                            <p class="availability in-stock">
                                <span class="label"><?php echo $this->helper('catalog')->__('Availability:') ?></span>
                                <span class="value"><?php echo $this->helper('catalog')->__('In stock') ?></span>
                            </p> 
                        <?php else: ?>
                            <p class="availability out-of-stock">
                                <span class="label"><?php echo $this->helper('catalog')->__('Availability:') ?></span>
                                <span class="value"><?php echo $this->helper('catalog')->__('Out of stock') ?></span>
                            </p>
                        <?php endif; ?>
                    </div>
                    <?php echo $abstractBlock->getPriceHtml($_item, true, '-related') ?>
                    <button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button btn-cart"
                            onclick="setLocation('<?php echo $abstractBlock->getAddToCartUrl($_item) ?>')">
                        <span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                </li>
            <?php endforeach; ?>
        </ul>
        <script type="text/javascript">decorateList('crosssell-products-list', 'none-recursive')</script>
    </div>
<?php endif; ?>