<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Autorelated
 * @version    2.4.12
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$abstractBlock = $this->helper('awautorelated')->getAbstractProductBlock();
$collection = $this->getCollection();

if ($this->getPosition() == AW_Autorelated_Model_Source_Position::INSTEAD_NATIVE_RELATED_BLOCK) {

    $this->iterateBlock();

    if ($collection && $collection->getSize()) {
        $this->markAsShowed();
    } elseif ($this->showNativeBlock()) {
        echo $this->getParent()->getChildHtml('catalog-product-related');
    }
}
?>
<?php if ($collection && $collection->getSize()) : ?>
    <?php if (Mage::helper('awautorelated')->checkVersion('1.4')): ?>
        <div class="box-collateral box-up-sell container aw-arp-block-<?php echo $this->getData('id') ?>">
            <h2><?php echo $this->htmlEscape($this->getData('name')) ?></h2>
            <div class="block-content aw-arp-block-content">
    <?php else: ?>
        <div class="box base-mini mini-related-items aw-arp-block aw-arp-block-<?php echo $this->getData('id') ?>">
            <div class="head">
                <h4><?php echo $this->htmlEscape($this->getData('name')) ?></h4>
            </div>
            <div class="content aw-arp-block-content">
    <?php endif; ?>
                <ul class="container owl-carousell products-grid products-grid--max-6-col owl-carousel" id="related-product-table">
                    <?php foreach ($collection as $product) : ?>
                        <li class="item">
                            <a class="product-image" href="<?php echo $abstractBlock->getProductUrl($product) ?>"><img src="<?php echo $this->helper('catalog/image')->init($product, 'small_image')->resize(400) ?>" alt="<?php echo $this->htmlEscape($product->getName()) ?>" width="250" height="250" />
                                <?php // Cucardas (Databunch) on product page ?>
                                <?php echo $this->getLayout()->createBlock('labels/catalog_product')->setProduct($product)->toHtml(); ?>
                            </a>
                            <h3 class="product-name">
                                <a href="<?php echo $abstractBlock->getProductUrl($product) ?>"><?php echo $this->htmlEscape($product->getName()) ?></a>
                            <h3 />
                            <?php echo $abstractBlock->getPriceHtml($product, true, '-related') ?>
                            <?php if ($product->isSaleable()) : ?>
                              <div class="actions">
                                    <button type="button" title="<?php echo Mage::helper('core')->quoteEscape($this->__('Add to Cart')) ?>" class="button btn-cart" onclick="setLocation('<?php echo $abstractBlock->getAddToCartUrl($product) ?>')"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button>
                                </div>
                            <?php else : ?>
                                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
                            <?php endif ?>
                        </li>
                    <?php endforeach ?>
                </ul>
            </div>
        </div>
<?php endif;?>